const Database = require("better-sqlite3");

const db = new Database("db/database.db");

// criar banco
db.exec(`
    CREATE TABLE unidades (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        nome TEXT NOT NULL UNIQUE
    );

    CREATE TABLE ramais (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        numero TEXT NOT NULL,
        setor TEXT NOT NULL,
        responsavel TEXT,
        unidade_id INTEGER NOT NULL,
        deleted_at TEXT,
        updated_at TEXT,
        updated_by INTEGER,
        FOREIGN KEY (unidade_id) REFERENCES unidades(id)
    );

    CREATE TABLE emails (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        email TEXT NOT NULL,
        setor TEXT NOT NULL,
        responsavel TEXT,
        unidade_id INTEGER NOT NULL,
        deleted_at TEXT,
        updated_at TEXT,
        updated_by INTEGER,
        FOREIGN KEY (unidade_id) REFERENCES unidades(id)
    );

    CREATE TABLE usuarios (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        username TEXT NOT NULL UNIQUE,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL CHECK(role IN ('owner','admin')),
        unidade_id INTEGER,
        FOREIGN KEY (unidade_id) REFERENCES unidades(id)
    );

    CREATE TABLE auditoria (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        usuario_id INTEGER,
        acao TEXT,
        entidade TEXT,
        entidade_id INTEGER,
        diff TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE sessions (
        id TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL,
        created_at TEXT NOT NULL,
        expires_at TEXT NOT NULL,
        FOREIGN KEY (user_id) REFERENCES usuarios(id)
    );
`)

// inserir unidades
db.exec(`
    INSERT INTO unidades (nome)
    VALUES
        ('Rochedo-MS'),
        ('Nova Andradina-MS'),
        ('Barra dos Bugres-MT'),
        ('Pirapozinho-SP');
`)

// inserir ramais Rochedo - MS
db.exec(`
    INSERT INTO ramais (numero, setor, responsavel, unidade_id)
    VALUES
        ('1000', 'Recepção', 'Recepção Adm', 1),
        ('1011', 'Escritório', 'Erasmo Nogueira', 1),
        ('1020', 'Almoxarifado', 'Heitor Pio', 1),
        ('1021', 'Almoxarifado', 'Beatriz Silva', 1),
        ('1022', 'Almoxarifado', 'Cindiel Ortiz', 1),
        ('1023', 'Almoxarifado', 'Atendimento Balcão', 1),
        ('1090', 'Acerto de Gado', 'Leandro Ribeiro', 1),
        ('1091', 'Acerto de Gado', 'Christtiano Marchetti', 1),
        ('1060', 'Exportação', 'Matheus Bolzan', 1),
        ('1061', 'Exportação', 'João Oliveira', 1),
        ('1062', 'Exportação', 'Gustavo Gomes', 1),
        ('1070', 'Comercial', 'Fabio Bolzan', 1),
        ('1071', 'Comercial', 'Angelo Santos', 1),
        ('1080', 'Compra Almoxarifado', 'Cicero Filho', 1),
        ('1120', 'Fiscal', 'Lucilene Martins', 1),
        ('1121', 'Fiscal', 'Ana Anjos', 1),
        ('1122', 'Fiscal', 'Paulo Alves', 1),
        ('1010', 'Gerencial', 'Denis Volpi', 1),
        ('1500', 'Gerencial', 'Osni Walter', 1),
        ('1580', 'Gerencial', 'Amauri Nunes', 1),
        ('1210', 'Financeiro', 'Leonardo Santos', 1),
        ('1211', 'Financeiro', 'Gisele Franco', 1),
        ('1040', 'Contas a Pagar', 'Angela Santos', 1),
        ('1180', 'Diretoria', 'Sergio Capuci', 1),
        ('1200', 'Faturamento Saída', 'Wellington Larreia', 1),
        ('1201', 'Faturamento Saída', 'Gabriel Oliveira', 1),
        ('1202', 'Faturamento Saída', 'Lauany Costa', 1),
        ('1190', 'Faturamento de Entrada', 'Caique Franco', 1),
        ('1240', 'PCP', 'Vinicius Martins', 1),
        ('1241', 'PCP', 'Woshington Gonçalves', 1),
        ('1280', 'Psicologia', 'Leiriane Sousa', 1),
        ('1300', 'RH', 'Roni Dallazem', 1),
        ('1301', 'RH', 'Juliari Medeiros', 1),
        ('1302', 'RH', 'Daiane Gonçalves', 1),
        ('1303', 'RH', 'Raul Gomes', 1),
        ('1304', 'RH', 'Estagiario RH', 1),
        ('1306', 'RH', 'Ingles Santos', 1),
        ('1930', 'Assistência Social', 'Alcilene Nunes', 1),
        ('1310', 'Sala de Reunião', 'Sala de reunião ADM', 1),
        ('1311', 'Sala de Reunião', 'Sala de Treinamento', 1),
        ('1330', 'TI', 'TI Geral', 1),
        ('1331', 'TI', 'Guímel Batista', 1),
        ('1332', 'TI', 'Marcos Gonçalves', 1),
        ('1339', 'TI', 'Cleison Souza', 1),
        ('1400', 'Portaria', 'Portaria', 1),
        ('1510', 'PCM', NULL, 1),
        ('1560', 'Refeitório', 'Neiza Donatoni', 1),
        ('1580', 'Manutenção', 'Amauri Nunes', 1),
        ('1590', 'Elétrica', 'Edinei Schipanski', 1),
        ('1940', 'Berçario', NULL, 1),
        ('1980', 'Motoristas Dormitório', NULL, 1),
        ('1600', 'Garantia da Qualidade', 'Thayna Oliveira', 1),
        ('1601', 'Garantia da Qualidade', 'G.Q - Monitores', 1),
        ('1602', 'Garantia da Qualidade', 'Garantia da Qualidade', 1),
        ('1603', 'Garantia da Qualidade', 'Sup Garantia', 1),
        ('1610', 'Embalagem Secundária - Desossa', 'Emabalagem Secundária', 1),
        ('1640', 'Embalagem Secundária - Desossa', 'Embalagem Mezanino', 1),
        ('1641', 'Embalagem Secundária - Desossa', 'Estoque Embalagem', 1),
        ('1620', 'Embarque', 'Expedição de caixas', 1),
        ('1621', 'Embarque', 'Tendal Pendurado', 1),
        ('1742', 'Embarque', 'Corte/PH', 1),
        ('1630', 'Sala de Etiqueta', 'Sala de Etiquetas', 1),
        ('1650', 'Lavanderia', 'Lavanderia', 1),
        ('1850', 'Químicos', 'Sala de Químicos', 1),
        ('1670', 'Halal', 'Halal', 1),
        ('1501', 'Sala dos Encarregados', NULL, 1),
        ('1690', 'Instrumentação', 'Instrumentação', 1),
        ('1720', 'Abate', 'Analista Abate', 1),
        ('1721', 'Abate', 'Balança Abate', 1),
        ('1700', 'Curral', NULL, 1),
        ('1730', 'Desossa', 'Analista Desossa', 1),
        ('1740', 'Rastreabilidade', 'Leonardo Maas', 1),
        ('1741', 'Rastreabilidade', 'Rastreabilidade Insumos', 1),
        ('1750', 'Sala de Máquina', 'Sala de Maquinas', 1),
        ('1760', 'Miúdos', 'Sala de Etiquetas', 1),
        ('1761', 'Miúdos', 'Balança Secundaria', 1),
        ('1780', 'Transporte', 'Ademilson Rodrigues', 1),
        ('1781', 'Transporte', 'Alequessandro Souza', 1),
        ('1790', 'Transporte Boiadeiro', 'Romario - Frete Boiadeiro', 1),
        ('1800', 'SIF', 'Escritório', 1),
        ('1801', 'SIF', 'Paulo Hiane', 1),
        ('1802', 'SIF', 'Igor', 1),
        ('1803', 'SIF', 'Daniela', 1),
        ('1900', 'Segurança do Trabalho', 'Rosano Freitas', 1),
        ('1901', 'Segurança do Trabalho', 'Segurança do Trabalho', 1),
        ('1910', 'Medicina/Enfermaria', 'Enfermaria', 1),
        ('1920', 'Fisioterapia', 'Dayana Graças', 1);
`);

// inserir ramais Nova Andradina - MS
db.exec(`
    INSERT INTO ramais (numero, setor, responsavel, unidade_id)
    VALUES
        ('2000', 'Telefonista', 'Nilva', 2),
        ('2010', 'Gerente ADM', 'Evandro Félix', 2),
        ('2020', 'Almoxarifado Balcão', NULL, 2),
        ('2021', 'Almoxarifado NF', 'Jhonatan/Viviane', 2),
        ('2022', 'Almoxarifado', 'Marli', 2),
        ('2070', 'Conferencia', 'Vitor/Kalissia', 2),
        ('2071', 'Comercial Interno', 'Leandro', 2),
        ('2072', 'Comercial Interno', 'Ricardo', 2),
        ('2090', 'Compra de Gado', 'Edivan', 2),
        ('2091', 'Compra de Gado', 'Romenir', 2),
        ('2120', 'Fiscal', 'Lucineia', 2),
        ('2121', 'Fiscal', 'Luciano', 2),
        ('2170', 'Devolução', 'Michel', 2),
        ('2180', 'Diretoria', 'Clarindo Capuci', 2),
        ('2181', 'Diretoria', 'Irene Capuci', 2),
        ('2182', 'Diretoria', 'Osmar Capuci', 2),
        ('2190', 'Faturamento Entrada', 'Flavio/Cristian', 2),
        ('2200', 'Faturamento Saída', 'Andre/João', 2),
        ('2201', 'Faturamento Saída', 'Fabricio', 2),
        ('2210', 'Financeiro', 'Lucilene/Salete', 2),
        ('2240', 'PCP', 'Danilo', 2),
        ('2241', 'PCP', 'Caique/Antonio', 2),
        ('2250', 'P&D', 'James/Wilson', 2),
        ('2280', 'Psicologia', 'Izabelle', 2),
        ('2300', 'RH', 'Alan', 2),
        ('2301', 'RH', 'Pedro/Vanessa', 2),
        ('2310', 'Sala Reunião / Treinamentos / Auditório', NULL, 2),
        ('2330', 'TI', 'Nova Andradina', 2),
        ('2331', 'TI', 'Hilderson', 2),
        ('2332', 'TI', 'Kaue', 2),
        ('2333', 'TI', 'William', 2),
        ('2400', 'Portaria 2400', NULL, 2),
        ('2500', 'Gerente Industrial', 'Luiz Fernando', 2),
        ('2510', 'PCM', 'Paola/Carol', 2),
        ('2511', 'PCM', 'Daniel', 2),
        ('2560', 'Nutricionista', 'Ariane', 2),
        ('2561', 'Cozinha / Refeitório', NULL, 2),
        ('2600', 'Coord. G.Q', 'Pamela', 2),
        ('2601', 'Garantia da Qualidade', NULL, 2),
        ('2620', 'Embarque A', 'Andre/Sergio', 2),
        ('2621', 'Embarque Caixaria', 'Rafael', 2),
        ('2650', 'Lavanderia', NULL, 2),
        ('2660', 'Graxaria', NULL, 2),
        ('2670', 'Halal', NULL, 2),
        ('2700', 'Curral', NULL, 2),
        ('2720', 'Abate', 'Aurilei', 2),
        ('2721', 'Abate', 'DIF', 2),
        ('2722', 'Abate', 'Apontadora', 2),
        ('2730', 'Desossa', 'Bruna', 2),
        ('2731', 'Desossa', 'Luiz Sobral', 2),
        ('2732', 'Desossa Dianteiro', NULL, 2),
        ('2740', 'Rastreabilidade', NULL, 2),
        ('2750', 'Sala de Máquinas', 'Givaldo', 2),
        ('2760', 'Miúdos', NULL, 2),
        ('2780', 'Transporte', 'Weverton', 2),
        ('2781', 'Transporte', 'Kauã/Danillo', 2),
        ('2800', 'SIF', NULL, 2),
        ('2801', 'SIF', 'Marcos', 2),
        ('2900', 'Segurança do Trabalho 2900', NULL, 2),
        ('2910', 'Medicina / Enfermaria', NULL, 2),
        ('2920', 'Fisioterapia', NULL, 2),
        ('2950', 'Alojamento', NULL, 2);
`);

// inserir ramais Barra dos Bugres - MT
db.exec(`
    INSERT INTO ramais (numero, setor, responsavel, unidade_id)
    VALUES
        ('3000', 'Telefonista – Adm', 'Karin', 3),
        ('3001', 'Telefonista – Adm', 'Karin', 3),
        ('3010', 'Adm Gerente', 'Sr. Geiser', 3),
        ('3020', 'Almox', 'Gisele', 3),
        ('3040', 'Adm Conferência', 'Carla', 3),
        ('3060', 'Adm Exportação', 'Marcelo', 3),
        ('3061', 'Adm Exportação', 'Rodolfo', 3),
        ('3070', 'Adm Vendas', 'Elias', 3),
        ('3080', 'Compras – Almoxarifado', 'Patricia', 3),
        ('3090', 'Adm Compras de Bovino', 'Maurício', 3),
        ('3091', 'Adm Compras de Bovino', 'Ricardo', 3),
        ('3120', 'Adm Escrita Fiscal', 'Fernandes', 3),
        ('3121', 'Adm Escrita Fiscal', 'Micaelle', 3),
        ('3180', 'Adm Diretoria', 'Sr. Osmar', 3),
        ('3181', 'Adm Diretoria', 'D. Rosângela', 3),
        ('3190', 'Adm Fat. Entrada', 'Ângela', 3),
        ('3200', 'Adm Faturista', 'Adeleoner', 3),
        ('3210', 'Adm Financeiro', 'Allan', 3),
        ('3240', 'Adm PCP', 'Josimar', 3),
        ('3280', 'Psc. – RH', 'Adriana', 3),
        ('3300', 'RH', 'Carlos', 3),
        ('3301', 'RH', 'Bruna', 3),
        ('3302', 'RH', 'Keven', 3),
        ('3320', 'Adm Sustentabilidade', 'Leonardo', 3),
        ('3321', 'Adm Sustentabilidade', 'Moacir', 3),
        ('3330', 'Adm TI', 'Silvio', 3),
        ('3331', 'Suporte/TI', 'Gustavo', 3),
        ('3400', 'Portaria', NULL, 3),
        ('3500', 'Gerente Industrial', 'Sr. Silmair', 3),
        ('3510', 'PCM', 'Mylleni', 3),
        ('3511', 'Coor. de Manut. - PCM', 'Marcio', 3),
        ('3560', 'Nutrição', 'Tatiana', 3),
        ('3600', 'Garantia da Qualidade', NULL, 3),
        ('3601', 'GQ', 'Roberta/Thamires', 3),
        ('3610', 'Embalagem Secundária - Ind', NULL, 3),
        ('3620', 'Tendal - Ind', NULL, 3),
        ('3621', 'Embarque de Caixa - Ind', NULL, 3),
        ('3640', 'Estoque de Embalagem', 'Josmiro', 3),
        ('3660', 'Graxaria - Ind', NULL, 3),
        ('3690', 'Instrumentação', 'Wilson', 3),
        ('3700', 'Curral - Ind', NULL, 3),
        ('3720', 'Abate - Balança – Ind', NULL, 3),
        ('3721', 'Abate - Rastreabilidade – Ind', NULL, 3),
        ('3730', 'Desossa - Ind', NULL, 3),
        ('3750', 'Sala de Maquinas - Ind', NULL, 3),
        ('3760', 'Miudos - Balança – Ind', NULL, 3),
        ('3761', 'Miudos Sala de Higienização - Ind', NULL, 3),
        ('3780', 'Transporte Frot Int', 'Enc. Tran.', 3),
        ('3790', 'Adm Trans Boiadeiro', 'Marcos', 3),
        ('3800', 'SIF Secretária', 'Hemily', 3),
        ('3801', 'SIF', 'Rafaelli', 3),
        ('3802', 'SIF - AFFA', NULL, 3),
        ('3803', 'SIF - AFFA', NULL, 3),
        ('3900', 'SESMT Seg do Trabalho', 'Israel', 3),
        ('3910', 'Ambulatório', 'Keila', 3);
`);

// inserir ramais Pirapozinho - SP
db.exec(`
    INSERT INTO ramais (numero, setor, responsavel, unidade_id)
    VALUES
        ('4000', 'Recepção Adm', 'Josie Belem', 4),
        ('4010', 'Remessa', 'Bruno Puro', 4),
        ('4011', 'Controladoria', 'Cristiano Garcia', 4),
        ('4020', 'Almoxarifado', 'Gabriel Olimpio', 4),
        ('4021', 'Almoxarifado', 'Balcão', 4),
        ('4022', 'Almoxarifado', 'Vitor Santos', 4),
        ('4023', 'Almoxarifado', 'Recebimento', 4),
        ('4030', 'Acerto de Gado', 'Renato Pucci', 4),
        ('4031', 'Acerto de Gado', 'Iago Oliveira', 4),
        ('4060', 'Exportação', 'Gustavo Borba', 4),
        ('4061', 'Exportação', 'Rafael Barros', 4),
        ('4062', 'Exportação', 'Mauricio Castro', 4),
        ('4063', 'Exportação', 'Lorena Rosa', 4),
        ('4064', 'Exportação', 'Alesca Nascimento', 4),
        ('4065', 'Exportação', 'Alex Nascimento', 4),
        ('4066', 'Exportação', 'Fernanda Queiroz', 4),
        ('4070', 'Comercial Interno', 'Luiz Eugenio', 4),
        ('4071', 'Comercial Interno', 'Ricardo Dalefe', 4),
        ('4072', 'Comercial Interno', 'Lucas Ranhi', 4),
        ('4073', 'Comercial Interno', 'Victor padovan', 4),
        ('4074', 'Comercial Interno', 'Victor moraes', 4),
        ('4075', 'Comercial Interno', 'Claudio Costa', 4),
        ('4076', 'Comercial Interno', 'Robson Silva', 4),
        ('4080', 'Compra Almoxarifado', 'Ivanei Souza', 4),
        ('4081', 'Compra Almoxarifado', 'Anderson Vieira', 4),
        ('4082', 'Compra Almoxarifado', 'Luiz Serafim', 4),
        ('4083', 'Compra Almoxarifado', 'Wesley Bueno', 4),
        ('4084', 'Compra Almoxarifado', 'Heverton Santana', 4),
        ('4085', 'Compra Almoxarifado', 'Tamiris Rodrigues', 4),
        ('4086', 'Compra Almoxarifado', 'Eduardo Brandi', 4),
        ('4087', 'Compra Almoxarifado', 'Lais Oliveira', 4),
        ('4100', 'Contabilidade', 'Vagner Souza', 4),
        ('4101', 'Contabilidade', 'Ana Figueiredo', 4),
        ('4102', 'Contabilidade', 'Leandro Rondoni', 4),
        ('4103', 'Contabilidade', 'Juliana Sana', 4),
        ('4104', 'Contabilidade', 'Giovana Okuma', 4),
        ('4105', 'Contabilidade', 'Guilherme Camargo', 4),
        ('4106', 'Contabilidade', 'Luis Souza', 4),
        ('4110', 'Custo', 'Silvio Marques', 4),
        ('4111', 'Custo', 'Milton Neto', 4),
        ('4120', 'Fiscal', 'Sandro Guimaraes', 4),
        ('4121', 'Fiscal', 'Caio Carvalho', 4),
        ('4122', 'Fiscal', 'Alex Querubino', 4),
        ('4013', 'Auditora Interna', 'Lilian Grosso', 4),
        ('4130', 'Gerencial', 'Marcia Serafim', 4),
        ('4131', 'Gerencial', 'Nara Takahara', 4),
        ('4132', 'Gerencial', 'Stephani Cisilo', 4),
        ('4133', 'Gerencial', 'Paloma Mata', 4),
        ('4107', 'Gerencial', 'Lorena Monteiro', 4),
        ('4135', 'Gerencial', 'Jessica Souza', 4),
        ('4136', 'Gerencial', 'Marinalva Santos', 4),
        ('4140', 'Contas a Pagar', 'Adriana Magro', 4),
        ('4141', 'Contas a Pagar', 'Lauany Trava', 4),
        ('4142', 'Contas a Pagar', 'Fernando Vasconcelos', 4),
        ('4143', 'Contas a Pagar', 'Danilo Silva', 4),
        ('4144', 'Contas a Pagar', 'Clovis Piveta', 4),
        ('4145', 'Contas a Pagar', 'Adriene França', 4),
        ('4150', 'Contas a Receber', 'Edvaldo Pretti', 4),
        ('4151', 'Contas a Receber', 'Rafael Constantino', 4),
        ('4152', 'Contas a Receber', 'Eduardo Puro', 4),
        ('4153', 'Contas a Receber', 'Regina Veronezi', 4),
        ('4154', 'Contas a Receber', 'Gabriel Souza', 4),
        ('4155', 'Contas a Receber', 'Andreia Muramatsu', 4),
        ('4170', 'Devolução', 'Rogerio Nascimento', 4),
        ('4171', 'Devolução', 'Mateus Rocha', 4),
        ('4180', 'Diretoria', 'Claudinei Capuci', 4),
        ('4181', 'Diretoria', 'Fabrizzio Capuci', 4),
        ('4182', 'Diretoria', 'Osmar Capuci', 4),
        ('4183', 'Diretoria', 'Thiago Nunes', 4),
        ('4184', 'Diretoria', 'Cristina Capuci', 4),
        ('4185', 'Diretoria', 'Rosangela Capuci', 4),
        ('4186', 'Diretoria', 'Felipe Capuci', 4),
        ('4187', 'Diretoria', 'Lais Capuci', 4),
        ('4188', 'Diretoria', 'Leonardo Capuci', 4),
        ('4189', 'Diretoria', 'Gabriel Capuci', 4),
        ('4190', 'Diretoria', 'Paulo Capuci', 4),
        ('4191', 'Diretoria', 'Luis Capuci', 4),
        ('4200', 'Faturamento Saída', 'Nelson Suzuki', 4),
        ('4201', 'Faturamento Saída', 'Alessandro Nascimento', 4),
        ('4202', 'Faturamento Saída', 'Raphael Oliveira', 4),
        ('4203', 'Faturamento Saída', 'Sergio Svet', 4),
        ('4210', 'Faturamento Entrada', 'Emerson Paz', 4),
        ('4220', 'Jurídico', 'Rangel Filho', 4),
        ('4221', 'Jurídico', 'Mau Borges', 4),
        ('4222', 'Jurídico', 'Luciana Zanin', 4),
        ('4240', 'PCP', 'Leandro Oliveira', 4),
        ('4241', 'PCP', 'Fernando Pereira', 4),
        ('4242', 'PCP', 'Daniel Zorzato', 4),
        ('4243', 'PCP', 'Derick Vida', 4),
        ('4250', 'PED', 'Aline Pessim', 4),
        ('4251', 'PED', 'Guilherme Batista', 4),
        ('4270', 'Pricing', 'Rogerio Caraffa', 4),
        ('4280', 'Psicologia', 'Denise Alves', 4),
        ('4281', 'Psicologia', 'Leticia Goes', 4),
        ('4300', 'RH', 'Rogerio Neves', 4),
        ('4301', 'RH', 'Adamo Caires', 4),
        ('4302', 'RH', 'Luciana Vasconcelos', 4),
        ('4303', 'RH', 'Pablo Padoan', 4),
        ('4304', 'RH', 'Jaciele Oliveira', 4),
        ('4305', 'RH', 'Wesley Souza', 4),
        ('4310', 'Sala Reunião', 'Sala de reunião ADM', 4),
        ('4311', 'Sala Reunião', 'Auditório', 4),
        ('4320', 'Sustentabilidade', 'Marla Teixeira', 4),
        ('4330', 'TI Sistemas', 'Murilo Zamora', 4),
        ('4331', 'TI Sistemas', 'Hugo Dunde', 4),
        ('4332', 'TI Sistemas', 'Matheus Costa', 4),
        ('4333', 'TI Sistemas', 'Marcus Barros', 4),
        ('4334', 'TI Infra', 'Douglas Figueiredo', 4),
        ('4335', 'TI Infra', 'Kaio Oliveira', 4),
        ('4336', 'TI Infra', 'Renan Sapia', 4),
        ('4337', 'TI Infra', 'Diego Benevides', 4),
        ('4340', 'Transporte', 'Angelo Sugui', 4),
        ('4341', 'Transporte', 'Edimara Lima', 4),
        ('4342', 'Transporte', 'Juliano Abreu', 4),
        ('4343', 'Transporte', 'Eduardo Ferreira', 4),
        ('4344', 'Transporte', 'Fabio Aznar', 4),
        ('4400', 'Portaria', 'Portaria', 4),
        ('4500', 'Administração Industrial', 'Jose Santana', 4),
        ('4510', 'PCM', 'Carlos Veronez', 4),
        ('4511', 'PCM', 'Tales Geraldino', 4),
        ('4512', 'PCM', 'João Cruz', 4),
        ('4540', 'Balanção', 'Balança Patio', 4),
        ('4550', 'Construção Civil', 'Construção Civil', 4),
        ('4560', 'Refeitório', 'Michelli Bassiquete', 4),
        ('4580', 'Manutenção', 'Rodrigo Rocha', 4),
        ('4590', 'Elétrica', 'Robson Barbosa', 4),
        ('4600', 'Garantia da Qualidade', 'Marcela Fernandez', 4),
        ('4601', 'Garantia da Qualidade', 'Daniele Maximo', 4),
        ('4602', 'Garantia da Qualidade', 'Thaine Ramos', 4),
        ('4603', 'Garantia da Qualidade', 'Lais Aleixo', 4),
        ('4604', 'Garantia da Qualidade', 'Tatiane Ganda', 4),
        ('4605', 'Garantia da Qualidade', 'Sara Puro', 4),
        ('4606', 'Garantia da Qualidade', 'Sala Documentos', 4),
        ('4607', 'Garantia da Qualidade', 'Devolução', 4),
        ('4610', 'Embalagem Secundária', 'Emabalagem Secundária', 4),
        ('4620', 'Embarque', 'Valdir (Tendal)', 4),
        ('4621', 'Embarque', 'Tiago (Carreg Desossa)', 4),
        ('4622', 'Embarque', 'Vitor (Carreg Miudos)', 4),
        ('4630', 'Sala de Etiqueta', 'Sala de Etiqueta', 4),
        ('4650', 'Lavanderia', 'Lavanderia', 4),
        ('4660', 'Graxaria', 'Graxaria', 4),
        ('4670', 'Halal', 'Cibal Halal', 4),
        ('4680', 'Higienização', 'Higienização', 4),
        ('4690', 'Instrumentação', 'Instrumentação', 4),
        ('4720', 'Abate', 'Abate', 4),
        ('4721', 'Abate', 'Balança Abate (Rodrigo)', 4),
        ('4722', 'Abate', 'Silvano', 4),
        ('4730', 'Desossa', 'Desossa', 4),
        ('4750', 'Sala de Máquina', 'Odalton Santos', 4),
        ('4751', 'Sala de Máquina', 'Sala de Maquinas', 4),
        ('4760', 'Miúdos', 'Miúdos', 4),
        ('4780', 'Rastreamento', 'Rastreamento 1', 4),
        ('4781', 'Rastreamento', 'Rastreamento 2', 4),
        ('4790', 'Curral / Boiadeiro', 'Ednei Francisco', 4),
        ('4791', 'Curral / Boiadeiro', 'Sergio Occulati', 4),
        ('4792', 'Curral / Boiadeiro', 'Renato Velasco', 4),
        ('4793', 'Curral / Boiadeiro', 'Balança Recebimento', 4),
        ('4794', 'Curral / Boiadeiro', 'Evandro Oliveira', 4),
        ('4800', 'SIF', 'Odelcio Ferreira', 4),
        ('4801', 'SIF', 'Raissa Suzuki', 4),
        ('4802', 'SIF', 'Recepção(Rogerio Silva)', 4),
        ('4803', 'SIF', 'Balcão (Lucas Vicente)', 4),
        ('4804', 'SIF', 'Thiago Pereira', 4),
        ('4900', 'Segurança do Trabalho', 'Cleber Jordão', 4),
        ('4901', 'Segurança do Trabalho', 'Segurança do Trabalho', 4),
        ('4910', 'Enfermaria', 'Enfermaria', 4),
        ('4920', 'Fisioterapia', 'Sergio Corazza', 4),
        ('4921', 'Fisioterapia', 'Sergio Corazza (Sala Fisio)', 4);
`);

console.log("Banco criado");
db.close();
